[tool.briefcase]
project_name = "busca_previsao"
bundle = "com.previsao"
version = "0.0.1"
url = "https://previsao.com/busca_previsao"
license = "BSD license"
author = 'Isaias'
author_email = "isaias@previsao.com"

[tool.briefcase.app.busca_previsao]
formal_name = "busca_previsao"
description = "buscar previsao"
icon = "src/busca_previsao/resources/busca_previsao"
sources = ['src/busca_previsao']
requires = [
]


[tool.briefcase.app.busca_previsao.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.busca_previsao.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.busca_previsao.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.busca_previsao.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.busca_previsao.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.busca_previsao.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.busca_previsao.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.busca_previsao.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
